const personService = require('../services/personService');
const relationshipService = require('../services/relationshipService');

/**
 * Generate AI Biography
 * @route POST /api/ai/generate-biography
 */
const generateBiography = async (req, res, next) => {
  try {
    const { person_id } = req.body;
    if (!person_id) {
      return res.status(400).json({ error: true, message: 'person_id is required' });
    }

    // Fetch person details
    const person = await personService.getPersonById(person_id);
    if (!person) {
      return res.status(404).json({ error: true, message: 'Person not found' });
    }

    const relationships = await relationshipService.getRelationshipsByPerson(person_id);

    // AI Generation Logic (Placeholder)
    // Here we would typically call OpenAI or Anthropic API.
    // e.g. const response = await openai.createCompletion({ prompt: `Write a bio for ${person.first_name}...` });

    const relSummary = relationships.length > 0
      ? `had ${relationships.length} closely documented relationships`
      : 'had a quiet documented relationship history';

    const origin = person.birth_place ? ` in ${person.birth_place}` : '';
    const birthStr = person.birth_date ? `born on ${new Date(person.birth_date).getFullYear()}${origin}` : 'with an unknown birthdate';

    const mockedAiBio = `(Generated by AI): ${person.first_name} ${person.last_name || ''} was ${birthStr}. Working as a ${person.occupation || 'dedicated family member'}, they ${relSummary}. Their legacy continues to live on within the documented nodes of this family tree.`;

    // Optionally save the generated bio back to the person's profile
    await personService.updatePerson(person_id, { bio: mockedAiBio });

    res.status(200).json({ biography: mockedAiBio });
  } catch (error) {
    next(error);
  }
};

module.exports = {
  generateBiography
};
